### ISSUE TITLE
native node.js crypto vs aes-js

### ISSUE THREAD

**Issue by mvayngrib** [DavidTanner/nodecredstash#27]
thanks for making this port!

is there any reason you chose to use aes-js instead of node.js crypto? You'll get better performance with native, and if you want to support the browser, you don't need to do anything special as browserify/webpack will plug in crypto-browserify automatically

**Comment by DavidTanner** [comment]
You are welcome to add a pull request that switches it out.

**Comment by mvayngrib** [comment]
@DavidTanner cool, one of these days. I forked and got a bit carried away: https://github.com/tradle/credstash (s3 backend support, CLI, and some general refactoring)

**Comment by DavidTanner** [comment]
I have a CLI in a separate repo.  Mostly this needs to fit the requirements set in the main credstash application.

**Comment by mvayngrib** [comment]
cool, makes sense to separate
