### ISSUE TITLE
FR: getAllSecrets  - dropPrefix option to go with startsWith

### ISSUE THREAD

**Issue by d1manson** [DavidTanner/nodecredstash#29]
**Feature Request**
When  calling `getAllSecrets({startsWith: "some/prefix/"})` it would be nice to be able to have some clean way of dropping the prefix from all the returned secrets, for example by adding `dropPrefix: "some/prefix/"`.

Obviously this can be done outside of this package, but it would be nice to include it to help with reading namespaced secrets.

Thanks!

**Comment by DavidTanner** [comment]
Since this is a supposed to be a port of the original credstash, I would expect it to follow the spec they designed.  I haven't looked at this project for a while, is that something they offer?
