### ISSUE TITLE
KMSOpts Are Not Respected in `getSecret` and Friends.

### ISSUE THREAD

**Issue by Seacant** [DavidTanner/nodecredstash#38]
Calls to `getSecret` and `getAllVersions` are creating their own KMSClient, thus ignoring the KMSOpts passed to `this.#kmsClient`.

https://github.com/DavidTanner/nodecredstash/blob/8bde68e9d7650ca3cb5ca87b1368dc2527d47252/src/index.ts#L112

I'm happy to submit a PR, but it would be helpful to know if there's a reason it's creating its own client, and whether it would be better to re-use the class variable or keep re-creating it per call, and just start passing in KMSOpts.

**Comment by DavidTanner** [comment]
I'm not sure there was a reason, as the methods can't be used without calling new on the Class.
