### ISSUE TITLE
Cannot `require()` package

### ISSUE THREAD

**Issue by IgnacioPinedo** [DavidTanner/nodecredstash#39]
I've used `nodecredstash@2.0.2` for a while now, but wanted to upgrade to leverage the `aws-sdk` v3 separate modules and decreased `node_modules` folder size. Unfortunately the repo I use it in doesn't support ES6 and I can't `require()` the package. This is the error I'm seeing:
```
/.../node_modules/nodecredstash/src/index.js:13
import { KMSClient } from '@aws-sdk/client-kms';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
It would be nice if the package was imported using CommonJS instead of ES6, that way it could be used in both ES6 and non-ES6 repos.

To reproduce you only need to try and `require()` the package in any file. An easy way to do this, is by going to the [npm package RunKit](https://npm.runkit.com/nodecredstash) and clicking run.

**Comment by IgnacioPinedo** [comment]
All that would be needed is just update the `tsconfig.json` file to have a `compilerOptions.modul` set to `CommonJS`.

**Comment by HenryLuoOne** [comment]
I have same issue as well (version 2 is working, but not version 3), seeing same runtime error.

**Comment by cherath** [comment]
I have the same issue. I have to move to v3.0.0.0 and now getting the same error. How did you resolve it?

**Comment by IgnacioPinedo** [comment]
Just as a note, we still have not resolved this. Currently I have all my functions using AWS v3 expect credstash which is still using v2 due to this issue.

**Comment by IgnacioPinedo** [comment]
Just waiting until it's released and I'll close the issue. The action to release is failing due to a token issue.

**Comment by cherath** [comment]
Hi All,
Thanks for letting us know.

Kind Regards,
Chulani
________________________________
