### ISSUE TITLE
Allow passing custom endpoints into underlying AWS clients

### ISSUE THREAD

**Issue by ajmath** [DavidTanner/nodecredstash#7]
To facilitate talking to a local dynamoDB instance, we need the ability to pass in a different endpoint parameters to KMS and DynamoDB. Because the same `awsOpts` param is shared for dynamo and KMS, it's not possible to change the endpoint.

I would propose two new items added to the high-level configuration (not `awsOpts`): `dynamoEndpoint` and `kmsEndpoint` that get merged into the respective `awsOpts` objects.

**Comment by DavidTanner** [comment]
Can you submit a pull request with said functionality and a test?
